fullnameOverride: prometheus
defaultRules:
  create: false
  disabled:
    KubeletDown: true
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    # Remove if not using Prometheus on a sub-path behind reverse proxy
    routePrefix: /prometheus/
    externalUrl: /prometheus/
    additionalConfig:
      otlp:
        promoteResourceAttributes:
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.availability_zone
          - cloud.region
          - container.name
          - deployment.environment.name
          - k8s.cluster.name
          - k8s.container.name
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.replicaset.name
          - k8s.statefulset.name
        # translationStrategy: NoUTF8EscapingWithSuffixes
        translationStrategy: UnderscoreEscapingWithSuffixes
    retention: 1d
    tsdb:
      outOfOrderTimeWindow: 30m
    enableRemoteWriteReceiver: true
    enableFeatures:
      - extra-scrape-metrics
      - auto-reload-config
      - remote-write-receiver
      - web.enable-otlp-receiver
      - otlp-deltatocumulative
  podMonitorNamespaceSelector:
    matchNames:
      - open-telemetry
      - prometheus
      - cert-manager
      - default
      - kube-system
      - ingress-nginx
grafana:
  enabled: false
prometheusOperator:
  admissionWebhooks:
    certManager:
      enabled: true
