loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true

lokiCanary:
  extraArgs:
    - -tenant-id=kind-loki-canary
  extraEnv:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=loki-canary,application=loki-canary"

minio:
  enabled: true
  users:
    - accessKey: loki-user
      secretKey: supersecretpassword
      policy: readwrite
    - accessKey: tempo-user
      secretKey: supersecretpassword
      policy: readwrite
    - accessKey: mimir-user
      secretKey: supersecretpassword
      policy: readwrite
  buckets:
    # Buckets used by Grafana Loki
    - name: chunks
      policy: none
      purge: false
    - name: ruler
      policy: none
      purge: false
    - name: admin
      policy: none
      purge: false
    # Buckets used by Grafana Tempo
    - name: tempo-traces
      policy: none
      purge: false
    # Buckets used by Grafana Mimir
    - name: mimir-tsdb
      policy: none
      purge: false
    - name: mimir-ruler
      policy: none
      purge: false
  persistence:
    size: 5Gi
    annotations: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
